### ISSUE TITLE
Error viewing plot

### ISSUE THREAD

**Issue by bheimbu** [acvill/bracken_plot#3]
Hi @acvill,

I cannot use the app with my [merged_bracken_F.txt](https://github.com/acvill/bracken_plot/files/12077511/merged_bracken_F.txt) file. I have used your [bracken_plot application](https://acvill.shinyapps.io/bracken_plot/). The error message doesn't help at all, so I'm writing here.

Cheers Bastian

**Comment by bheimbu** [comment]
Hi @acvill,

I have found the solution by myself. When I read in my bracken file into R (using the Rmarkdown script), it takes the taxonomy_lvl column as logical and changes every instance of "F" ("F" = Family level) into "FALSE". So I have used following R code to change the column from logical to character and every instance of "FALSE" to "F":

`bracken <- read_tsv("~/Schreibtisch/merged_bracken_F.txt")
bracken$taxonomy_lvl <- as.character(bracken$taxonomy_lvl)
bracken$taxonomy_lvl[bracken$taxonomy_lvl=="FALSE"]<-"F"`

This may also explain why I cannot use the bracken_plot application.

Cheers Bastian

**Comment by bheimbu** [comment]
Hi @acvill,

I have found the solution by myself. When I read in my bracken file into R (using the Rmarkdown script), it takes the taxonomy_lvl column as logical and changes every instance of "F" ("F" = Family level) into "FALSE". So I have used following R code to change the column from logical to character and every instance of "FALSE" to "F":

`bracken <- read_tsv("merged_bracken_F.txt")
bracken$taxonomy_lvl <- as.character(bracken$taxonomy_lvl)
bracken$taxonomy_lvl[bracken$taxonomy_lvl=="FALSE"]<-"F"`

This may also explain why I cannot use the bracken_plot application.

Cheers Bastian

**Comment by acvill** [comment]
Hi @bheimbu, thank you for reporting this bug. If you want to submit a pull request for your fix, I would be happy to review and merge it. Otherwise, I can just implement  myself at some later date. 

An alternative fix is to specify `col_types` when the data are read in:
```{r}
notlogical <- cols(taxonomy_lvl = col_character())
plot_bracken(file = read_tsv("data/merged_bracken_F.txt",
                             col_names = TRUE,
                             col_types = notlogical),
             top = 10,
             pal = "dcdcdc,7f0000,006400,708090,808000,483d8b,000080,9acd32,8b008b,66cdaa",
             otherColor = "gray")
```

**Comment by bheimbu** [comment]
Hi @acvill,

I don't want to submit a pull request, go ahead please. Thanks for your fast reply and your more elegant solution to the problem ;)

Cheers Bastian

**Comment by acvill** [comment]
Fixed with commit https://github.com/acvill/bracken_plot/commit/6f5e6d7b05a85dd2fca6ca41c47340e4cf850bb4
