### ISSUE TITLE
Plot not generated

### ISSUE THREAD

**Issue by In2S** [acvill/bracken_plot#4]
Hello acvill,
I have tried to run bracken_plot, however no plot is being generated.
![image](https://github.com/acvill/bracken_plot/assets/86762450/8f03083f-6bce-4e7b-9c40-a194a1b003d5)
![image](https://github.com/acvill/bracken_plot/assets/86762450/c33bc982-1832-4815-9da8-c8a7d71aff78)

I am getting this outcome.

Please look into this.

With regrads,
In2S

**Comment by acvill** [comment]
Hi @In2S -- this could be a number of things. I restarted the application and successfully made a plot using one of the [example files](https://github.com/acvill/bracken_plot/tree/main/example_data_bracken), so it's not a server issue. If you can try again with one of the example files and it works, then it's likely an issue with your input. The app might hang if the size of the input file requires too many resources to process. Try subsetting your data using the `Maximum number of taxa to plot` field.

**Comment by In2S** [comment]
Issue resolved.
Thank you for your reply.

**Comment by In2S** [comment]
Hello,

bracken_plot is generating plots in Linux. However, it is running but not
generating plots in Windows.
Can you help me with this?

With regards,
Indu

With regards,
*In2K/इन2क*

*Satyanveshi (to seek the truth)/सत्यान्वेषी(सत्य की खोज में)*

[image: International Year of Basic Sciences for Development]

**Comment by acvill** [comment]
Since the app is web-based, there's no simple reason why it wouldn't work on the same browser across operating systems. I'm currently using Chrome v115.0.5790.171 on a Windows 11 machine, and bracken_plot works fine. If you continue running into issues on Windows, you could try downloading the [bracken_plot.Rmd notebook](https://github.com/acvill/bracken_plot/blob/main/bracken_plot.Rmd) and creating plots locally in RStudio.

**Comment by In2S** [comment]
Ok, thank you for your quick response.

**Comment by In2S** [comment]
Hello Vill,

The maximum number of samples that can be plotted is limited. How can I
increase the limit.
I am editing App.R file:
[image: image.png]
But it is not working. IS there something wrong with it?
Thank you in advance.

With regards,
*In2K/इन2क*

*Satyanveshi (to seek the truth)/सत्यान्वेषी(सत्य की खोज में)*

[image: International Year of Basic Sciences for Development]

**Comment by acvill** [comment]
Are you using the app.R file to run a local instance of the bracken_plot app in shiny? Instead, if you are trying to recreate the relative abundance plots locally, I would recommend downloading the [bracken_plot.Rmd notebook](https://github.com/acvill/bracken_plot/blob/main/bracken_plot.Rmd) and running the `plot_bracken()` function with your data in R / RStudio. You can then make adjustments to the ggplot portion of the function to accommodate more samples.

**Comment by In2S** [comment]
Thank you for your response. It is working fine. How can I cite your
Utility in research paper, if there is any paper or link for citation.
Please share it.

With regards,
*In2K/इन2क*

*Satyanveshi (to seek the truth)/सत्यान्वेषी(सत्य की खोज में)*

[image: International Year of Basic Sciences for Development]

**Comment by acvill** [comment]
Glad it's working for you. There is no publication associated with the app. You can cite the GitHub repository as follows:

> Vill, A. C. (2023). bracken_plot: a Shiny app for taxonomic abundance visualization [Computer software]. https://github.com/acvill/bracken_plot

I would also recommend citing kraken2 and bracken.

https://doi.org/10.1186/s13059-019-1891-0
https://doi.org/10.7717/peerj-cs.104

**Comment by In2S** [comment]
I have used Kraken2 and Bracken, already cited.
Thank you.

With regards,
*In2K/इन2क*

*Satyanveshi (to seek the truth)/सत्यान्वेषी(सत्य की खोज में)*

[image: International Year of Basic Sciences for Development]

**Comment by In2S** [comment]
Greeting for the day,

I am trying to generate heatmap for beta-diversity obtained from bracken
files by following command:

python KrakenTools/DiversityTools/beta_diversity.py -i \
bracken_outputs/SRR14092160.bracken bracken_outputs/SRR14092310.bracken \
bracken_outputs/SRR14143424.bracken --type bracken

However, I am getting this error:
Error in heatmap(data) : 'x' must be a numeric matrix

This is the input file:
x	0	1	2	3	4	5	6	7	8	9	10	11	12	13	14
0	0.000	0.455	0.703	0.600	0.288	0.292	0.571	0.779	0.467	0.737	0.507	0.716	0.558	0.445	0.852
1	x.xxx	0.000	0.637	0.691	0.564	0.345	0.285	0.719	0.661	0.680	0.267	0.517	0.704	0.657	0.821
2	x.xxx	x.xxx	0.000	0.769	0.789	0.667	0.530	0.293	0.803	0.248	0.678	0.256	0.757	0.769	0.487
3	x.xxx	x.xxx	x.xxx	0.000	0.583	0.666	0.696	0.817	0.479	0.790	0.690	0.784	0.381	0.435	0.892
4	x.xxx	x.xxx	x.xxx	x.xxx	0.000	0.436	0.665	0.824	0.409	0.801	0.590	0.775	0.582	0.400	0.885
5	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	0.000	0.484	0.760	0.566	0.714	0.419	0.654	0.636	0.562	0.835
6	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	0.000	0.643	0.745	0.603	0.362	0.390	0.719	0.701	0.766
7	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	0.000	0.856	0.215	0.726	0.375	0.839	0.823	0.420
8	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	0.000	0.834	0.709	0.829	0.449	0.380	0.905
9	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	0.000	0.691	0.322	0.796	0.794	0.419
10	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	0.000	0.554	0.733	0.680	0.821
11	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	0.000	0.800	0.790	0.510
12	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	0.000	0.389	0.890
13	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	0.000	0.882
14	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	x.xxx	0.000

With regards,

Indu


With regards,
*In2K/इन2क*

*Satyanveshi (to seek the truth)/सत्यान्वेषी(सत्य की खोज में)*

[image: International Year of Basic Sciences for Development]
