### ISSUE TITLE
Viewing plot

### ISSUE THREAD

**Issue by kose-bioinfo** [acvill/bracken_plot#6]
Hi there,

This is a nice shiny app, thank you! and produces the plots I need. However, I have a few questions. When the number of taxa are reduced to say '20', does the app then calculate the top 20 taxa in the respective taxonomica levels? i.e. top 20 genera. Is there also a way to plot these by group/do you know another way to do stats and by group plotting for combined bracken outputs? 

Thanks!

**Comment by acvill** [comment]
Thanks for using the app.

Subsampling plots the *n* taxa with the greatest median relative abundances across samples. So, if you subsample to 20, the app will calculate median abundance values for each taxon, order the taxa by decreasing abundance, and assign colors to the top 20 most abundant taxa only, summing the per-sample abundances of remaining taxa and plotting as "other". 

There are a few ways to group the data. If you [download the R notebook](https://github.com/acvill/bracken_plot/blob/main/bracken_plot.Rmd), you can specify `position = "stack"` and `stat = "identity"` in `geom_bar()` to create a [grouped and stacked bar chart](https://guslipkin.medium.com/grouped-and-stacked-bar-charts-in-r-e5f5ac5637de). Easier yet, you can adjust the [width of the bars and aspect ratio of the plot](https://stackoverflow.com/a/50078025/7976890) until you get the desired look for your plot.

**Comment by kose-bioinfo** [comment]
Thank you very kindly for the response, it is greatly appreciated! I see what you mean about the grouped and stacked plots - thank you! However  I  was thinking more so about the grouping of sample types (with metadate information provided). This is primarily for group wise comparisons and also for alpha and beta diversity plotting of the bracken data. Is there a similar app/notebook for this that you are aware of?

**Comment by acvill** [comment]
> Is there a similar app/notebook for this that you are aware of?

Sadly no. I hope you find a solution!
